### ISSUE TITLE
unable to find package.json in module's subdirectory

### ISSUE THREAD

**Issue by Coderah** [yarnpkg/yarn#1910]
`yarn add gamepad` is resulting in an error:

`
error Couldn't find a package.json file in "./node_modules/gamepad/node_modules/node-pre-gyp"
`
and of course `node_modules doesn't exist within the `gamepad` directory, however `node-pre-gyp` does exist in `./node_modules` directly and it contains a `package.json` file.

I've attempted removing node_modules and running yarn again.

NOTE: I've replaced the long path to my project with simply `./`

yarn: v0.17.2
node: 6.9.1
ubuntu

**Comment by Coderah** [comment]
by running `yarn add node-pre-gyp` the issue is resolved, however there may still be a bug considering there is nothing that guided me to doing that, nor am I sure I should need to.

**Comment by Coderah** [comment]
the installation issue was resolved with the above, however actually requiring the module results in the same-ish errors, perhaps this is just due to the `gamepad` module doing something wrong.

**Comment by wyze** [comment]
I suspect this is due to `gamepad` defining `node-pre-gyp` in `bundledDependencies` but yarn is hoisting it up to the top level anyways.

**Comment by wyze** [comment]
Can still reproduce this on `0.17.4`.

**Comment by paralin** [comment]
I'm encountering this now as well.

**Comment by nwwells** [comment]
Seeing this in 0.18.0 as well. pre-installing `node-pre-gyp` doesn't resolve the issue for me.

**Comment by gabriel** [comment]
I think I have a similar problem, might be a dupe or might not, so created an issue here: https://github.com/yarnpkg/yarn/issues/2571

**Comment by rodrigopivi** [comment]
It's a problem with node-pre-gyp, the issue is already fixed at master, but not at the latest release (v0.6.32).

https://github.com/mapbox/node-pre-gyp/issues/262

**Comment by bestander** [comment]
merging with https://github.com/yarnpkg/yarn/issues/886
