### ISSUE TITLE
disable-progress config option

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#1956]
Make it possible to permanently disable progress-bar so would be no need to use `--disable-progress` in each command.

**Comment by olingern** [comment]
I can do this and make some minor improvements, too :)

**Comment by thetrompf** [comment]
I believe this one has been fixed in these commits f5d1ded5cc2f6010c478aa9b92f98679eba930eb 2971d856da3f2d43256cdc45a9531d68ee91b97d 5cd11467ee409adf877e8de808c02f89b6d37832 ?

**Comment by olingern** [comment]
The PR I'm working on would use the global yarn config to disable it for the user's machine. Currently, the flag is needed with each flag

**Comment by thetrompf** [comment]
Cool :) maybe you should ping this issue from the PR or the other way around. It is much easier to see what is in progress, especially when this issue is marked as "good first bug" so others don't start implementing it as well? :)

**Comment by kamilogorek** [comment]
This issue can be closed. It already works in `0.21.3`.

```
$ yarn config set no-progress
```

**Comment by raould** [comment]
I set the options for no-progress and no-color but I still get crazy escape sequence characters in my emacs buffer whenever I run yarn command like "yarn add" or even "yarn config list". Am I missing the point / is this unrelated? thank you...

```
$ yarn config list
^[[1Gyarn config v0.23.2
^[[1Ginfo yarn config
^[[1G{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/0.23.2 npm/? node/v4.2.6 linux x64',
  lastUpdateCheck: 1492408117628,
  'no-color': true,
  'no-progress': true }
^[[1Ginfo npm config
^[[1G{}
^[[1GDone in 0.05s.
```

**Comment by kamilogorek** [comment]
@raould can you check if it happens with you use `--disable-progress` directly?

**Comment by olingern** [comment]
@raould This --no-progress is only for the progress bar. The output you're getting just seems to be the the steps yarn goes through during installation
