### ISSUE TITLE
Resolutions inside a workspace package doesn't work

### ISSUE THREAD

**Issue by AvivRubys** [yarnpkg/yarn#5039]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
When using a `resolutions` property in an inner package on a dependency that gets hoisted up, the `resolutions` property is ignored. If moved to the root package, it resolves correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've prepared an [example repo](https://github.com/AvivRubys/workspace-resolution-example) with two branches - `resolution-in-root` and `resolution-in-same-package` that demonstrate this.
Simply checkout a branch, run `yarn`, and check the installed version of webpack. (Delete `node_modules` when moving between branches)
You'll see that on the `resolution-in-root` branch, the installed version of webpack is 3.8.1 as specified in the `resolutions` block, as opposed to the `resolution-in-same-package` where the webpack version will not be constrained by `resolutions`.

**What is the expected behavior?**
I would expect that if a dependency and a `resolutions` property that constrain it are in the same `package.json`, that the resolutions limitations will apply to the package, no matter where it gets hoisted to.

**Please mention your node.js, yarn and operating system version.**
```
$ node --version
v8.9.1

$ yarn --version
1.3.2

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B1003
```

**Comment by dvsekhvalnov** [comment]
+1 still an issue in latest 1.7.0

**Comment by buschtoens** [comment]
@jirutka you can set the resolutions in the workspace root `package.json`.

**Comment by arcanis** [comment]
@buschtoens is right - and while it looks simple in appearance, supporting nested resolutions in the way you expect isn't trivial. In the Yarn model, a same range always resolve to the exact same version, regardless of where they are on the dependency tree.

Due to this behavior, any custom resolution defined in a workspace would also apply on other workspaces, which would be counterintuitive. For this reason, the resolutions field is ignored in nested workspaces, and we instead force you to explicitly list them all in the root `package.json`.

**Comment by jirutka** [comment]
> you can set the resolutions in the workspace root package.json.

No, I've tried that, it doesn't work, resolution is just ignored.

**Comment by buschtoens** [comment]
@arcanis 

> In the Yarn model, a same range always resolve to the exact same version, regardless of where they are on the dependency tree.

Makes total sense and I can keep working with that model. But seeing that there is a [`nohoist` config](https://yarnpkg.com/blog/2018/02/15/nohoist/), in wishful thinking I would intuitively have expected workspace-local resolutions to cause these dependencies to not be hoisted and also override any potential matching workspace-global resolutions.

@jirutka 

> No, I've tried that, it doesn't work, resolution is just ignored.

What version of yarn are you on?

There's also a nasty bug with resolutions and `yarn add`: when you `yarn add` a dependency, yarn will complain about invalid lockfile entries an will then proceed to install all dependencies, as if there were no resolutions, even if they have beem correctly resolved before.

To fix this, it's usually enough to nuke the root `node_modules` directory and run `yarn` again. I don't know if this is a known issue, but a quic search did not bring it up yet, so I'll create a separate issue for this.

**Comment by arcanis** [comment]
> But seeing that there is a [`nohoist` config](https://yarnpkg.com/blog/2018/02/15/nohoist/)

Makes sense, but the `nohoist` option is a hack that we actively discourage people from using, only there because some packages don't play by the rules.

No package should *ever* rely on its hoisting. Doing it is similar to letting users walk on a rotted wood deck then suggesting them to send a complaint to their shoemakers when it finally breaks.

**Comment by jirutka** [comment]
> @buschtoens What version of yarn are you on?

1.9.4

> To fix this, it's usually enough to nuke the root node_modules directory and run yarn again.

I've tried that without success.

**Comment by nicolasv** [comment]
I'm kind of seeing the opposite, where the root `resolutions` doesn't seem to be respected?

For example, in the root `package.json` I have:
```
  "resolutions": {
    "@types/react": "16.4.2"
  }
```

If I do `yarn workspace foo add lodash` (or `cd packages/foo && yarn add lodash`), it doesn't respect the `@types/react` resolution and adds a new resolution:

```diff
diff --git a/yarn.lock b/yarn.lock
index 4b9c0f908..e3f5dd91e 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -2966,12 +2966,17 @@
     "@types/history" "*"
     "@types/react" "*"
 
-"@types/react@*", "@types/react@16.4.2", "@types/react@^0.14.44":
+"@types/react@*", "@types/react@16.4.2":
   version "16.4.2"
   resolved "https://registry.yarnpkg.com/@types/react/-/react-16.4.2.tgz#f1a9cf1ee85221530def2ac26aee20f910a9dac8"
   dependencies:
     csstype "^2.2.0"
 
+"@types/react@^0.14.44":
+  version "0.14.57"
+  resolved "https://registry.yarnpkg.com/@types/react/-/react-0.14.57.tgz#1878a8654fafdd1d381b8457292b6433498c5b62"
+  integrity sha1-GHioZU+v3R04G4RXKStkM0mMW2I=
+
 "@types/redis@*", "@types/redis@^2.8.6":
   version "2.8.6"
   resolved "https://registry.yarnpkg.com/@types/redis/-/redis-2.8.6.tgz#3674d07a13ad76bccda4c37dc3909e4e95757e7e"

```

However, if I copy the root `package.json`'s `resolutions` to `foo/package.json` then it respects the resolution when I do `yarn workspace foo add lodash`.

I'm not sure if this is intended behaviour or not.

**Comment by Jessidhia** [comment]
It seems that `yarn add` (and `yarn upgrade-interactive`, with or without `--latest`) do not respect resolutions, and create an already-stale `yarn.lock`. Re-running `yarn install` will re-resolve the packages again, this time according to `resolutions`.

**Comment by gitowiec** [comment]
I have the same problem. I just can't override @types/react with
```
  "resolutions": {
    "**/@types/react": "16.8.5"
  },
```
I have huge conflict of types in my monorepo and I don't know how to resolve it. Putting this with TypeScript config and Webpack config, I am really going gray... :(

**Comment by webberwang** [comment]
After investing into a yarn workspace mono-repo setup, I am utterly devastated to find out that module resolutions don't work properly. 

For a setup that is prone to version errors, this should be a priority!

**Comment by arcanis** [comment]
You wouldn't imagine the number of priorities that people think I should have 🙂

Yarn v2 will completely overhaul the resolution logic and will solve many shortcomings we have with the current one - afaik this particular issue is already fixed.

**Comment by HosseinAgha** [comment]
God this is so annoying 😭

**Comment by AndreLacasse** [comment]
Still happens to me with the version 1.21.1 and looks to be fixed with the last version 1.22.4. The issue is still open?

**Comment by anatol-grabowski** [comment]
Still happens to me on 1.22.4 and 1.22.10. 
Moving `resolutions` to the root `package.json` (kind of) solves the issue.
I also expect "workspace-local resolutions to cause these dependencies to not be hoisted and also override any potential matching workspace-global resolutions."

**Comment by olee** [comment]
I have the same issue even with yarn 2 :-/

**Comment by merceyz** [comment]
> I have the same issue even with yarn 2 :-/

@olee `yarn@>=2` only supports resolutions in the project root

**Comment by asvetly** [comment]
still actual with yarn@3.0.2

**Comment by jhowell-droit** [comment]
Still seems to be an issue in `v3.4.1`. If anyone knows how to get it working in this version I'd love to know!

**Comment by salazarm** [comment]
> You wouldn't imagine the number of priorities that people think I should have 🙂

> Yarn v2 will completely overhaul the resolution logic and will solve many shortcomings we have with the current one - afaik this particular issue is already fixed there.

Aged like milk

**Comment by tommymarshall** [comment]
Still an issue :( This is coming up more with our NextJS app expecting one version and a package with a hard dependency expecting another.

**Comment by SSTPIERRE2** [comment]
With pnpm I get a false positive in my monorepo with the error `The field "resolutions" was found in .../package.json This will not take effect. You should configure "resolutions" at the root of the workspace instead.` Where setting resolutions in the package i need it in actually works just fine, but setting it in the root package.json doesn't work at all.

**Comment by KostyaTretyak** [comment]
> Due to this behavior, any custom resolution defined in a workspace would also apply on other workspaces, which would be counterintuitive. For this reason, **the resolutions field is ignored in nested workspaces**, and we instead force you to explicitly list them all in the root `package.json`.

@arcanis, I wonder why you don't even issue warning logs in this case?

**Comment by arcanis** [comment]
We do, in all modern releases (ie >=2).

**Comment by zargold** [comment]
>[arcanis](https://github.com/arcanis) commented [3 weeks ago](https://github.com/yarnpkg/yarn/issues/5039#issuecomment-1684110498)
We do, in all modern releases (ie >=2).

These 2 messages are in conflict: 
>[jhowell-droit](https://github.com/jhowell-droit) commented [on Feb 21](https://github.com/yarnpkg/yarn/issues/5039#issuecomment-1438881183)
Still seems to be an issue in v3.4.1. If anyone knows how to get it working in this version I'd love to know!

I am also having it with: 
```
yarn --version
3.2.2
```

**Comment by arcanis** [comment]
The message I'm answering to is:

> I wonder why you don't even issue warning logs in this case

Modern releases don't support the `resolutions` setting anywhere else than the root, and we generate a warning when you accidentally do it.

I think I'm going to lock this thread, there isn't more to say around this topic on this repo.
