### ISSUE TITLE
Integrity checked failed error

### ISSUE THREAD

**Issue by tenjojeremy** [yarnpkg/yarn#7552]
When I try to install one of my packages from the Github Package Manager I get the error bellow:

Integrity checked failed for "@tenjojeremy/eslint-config" (none of the specified algorithms are supported)

![error](https://user-images.githubusercontent.com/25231946/64899136-357e4300-d647-11e9-8002-96e36a9a9255.jpg)

**Comment by oliverfernandez** [comment]
I have the same problem with version `1.17.3` in Mac OS

**Comment by eastroots92** [comment]
me too :sob:

**Comment by ycs77** [comment]
Same 😭

**Comment by wagich** [comment]
I have the same problem with the Github Package Registry.

Looking at the json response I get from `https://npm.pkg.github.com/` when fetching the package metadata (under the path `/versions/*/dist`), there is no `integrity` property and the `shasum` property is an empty string. If I get a package from the official npm registry, they are both present. Maybe the problem is with the Github Package Registry?

**Comment by tenjojeremy** [comment]
I asked Github support and this was their reply

> Currently the only documented support we have for installing npm packages is using the npm client.

I've tried this myself, and encountered the same error that you are seeing. I do understand that Yarn is hugely popular for managing JavaScript and NodeJs projects and have therefore flagged this with engineering to look into.

I don't currently have an ETA on this, however we would love to align support with all the popular development tools over time.

I'll keep you posted on updates, and you can also checkout https://github.blog

**Comment by ganmor** [comment]
We got it working by:
- Removing the yarn lock from the dependency ( in this case eslint-config )
- Adding update-checksum option to yarn install.

Along with the following npmrc.
```
always-auth=true
registry=https://npm.pkg.github.com/${org}
_authToken=${NPM_TOKEN_GITHUB}
//npm.pkg.github.com:_authToken=${NPM_TOKEN_GITHUB}
```

**Comment by browniefed** [comment]
The solution @ganmor presented worked great. Don't worry about a `.yarnrc`, just create a local `.npmrc` and things will work great.

If you want to verify what is happening just do an `yarn add @org/package --verbose` and look to see if you're getting a `401` unauthorized error. If so then this solution should work for you.

**Comment by birtles** [comment]
Note that there appears to be a tangentially related issue of authorization (sometimes?) being requested for public packages in the GitHub package registry producing similar symptoms (i.e. 401 errors despite the fact that authorization should not be required).

**Comment by tenjojeremy** [comment]
Fixed in Yarn version `1.19.1`

**Comment by tenjojeremy** [comment]
Fixed in Yarn version `1.19.1`

**Comment by amk221** [comment]
I still see this

```
verbose 1.669 Request "https://npm.pkg.github.com/@org%2fmy-package" finished with status code 200.
verbose 2.596 Error: No algorithms available for ""
    at Integrity.pickAlgorithm (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:32619:13)
    at Integrity.match (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:32604:24)
    at /usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:48145:58
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:315:13
```

**Comment by tenjojeremy** [comment]
Still present in yarn v1.19.1

**Comment by ryanjwilke** [comment]
I'm on yarn `1.19.1` and the issue still remains for me as well.

**Comment by negebauer** [comment]
The integrity checks fails with only some GitHub package registry packages. Some do have the `integrity` property and some don't. It's not consistent

**Comment by dmail** [comment]
GitHub package registry implemented integrity late. Package published before this date have no integrity property. I haven't retried to publish then download using yarn since but in theory recent package should be good.

**Comment by LinBoLen** [comment]
it works right now

**Comment by drewwyatt** [comment]
This is still failing for me. Anyone else?

**Comment by tenjojeremy** [comment]
@drewwyatt ✋

**Comment by rehos** [comment]
@drewwyatt Yes is it still failing.

**Comment by tenjojeremy** [comment]
Still failing

**Comment by baurine** [comment]
> We got it working by:
> 
> * Removing the yarn lock from the dependency ( in this case eslint-config )
> * Adding --update-checksums option to yarn install.
> 
> Along with the following npmrc.
> 
> ```
> always-auth=true
> registry=https://npm.pkg.github.com/${org}
> _authToken=${NPM_TOKEN_GITHUB}
> //npm.pkg.github.com:_authToken=${NPM_TOKEN_GITHUB}
> ```

works for me as well, thanks @ganmor

**Comment by tan-nhu** [comment]
I got it working by running all of these commands (fish):

```fish
set YARNCACHE (yarn cache dir); rm -rf $YARNCACHE; rm -rf node_modules;  yarn cache clean; yarn --update-checksums; yarn
```

**Comment by micahstubbs** [comment]
@ganmor's advice is useful for resolving complications from this issue https://github.com/postcss/autoprefixer/issues/1184
