### ISSUE TITLE
"[DEP0040] The `punycode` module is deprecated" with Node.js 21.x (Rev 2)

### ISSUE THREAD

**Issue by MikeMcC399** [yarnpkg/yarn#9013]
- re-open of issue #9005 (re-opened as new issue, since a new version of Yarn is involved)

## Description

```bash
yarn info
```

provokes a deprecation warning under [Node.js current version](https://nodejs.org/en) `21.x`.

> [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

## Versions

| Component      | Version  |
| -------------- | -------- |
| Yarn (Classic) | v1.22.21 |
| Node.js:       | ~~v21.2.0~~ v21.6.2  |

## Steps to reproduce

With Node.js ~~v21.2.0~~ v21.6.2 installed, execute:

```shell
npm install yarn@latest -g
yarn info yarn description
```

shows

```text
$ npm install yarn -g
changed 1 package in 909ms
$ yarn info yarn description
yarn info v1.22.21
(node:19052) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
📦🐈 Fast, reliable, and secure dependency management.
Done in 1.06s.
```

Further debug information is output by:

 ```shell
 NODE_OPTIONS='--trace-deprecation' yarn info yarn description
 ```

**Comment by MikeMcC399** [comment]
The issue is also reproducible with `yarn add`

```shell
npm install yarn@1.22.1 -g
mkdir yarn-test
cd yarn-test
yarn init -y
yarn add yarn
```

displays:

```text
yarn add v1.22.1
info No lockfile found.
[1/4] Resolving packages...
⠁ (node:15052) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ yarn@1.22.21
info All dependencies
└─ yarn@1.22.21
Done in 0.44s.
```

**Comment by kayac-chang** [comment]
I also encountered this issue, leave the version here for reference.


Component | Version
-- | --
Yarn (Classic) | v1.22.19
Node.js: | v21.2.0

**Comment by MikeMcC399** [comment]
@kayac-chang 
Yarn (Classic) `v1.22.19` has already been replaced by` v1.22.21`, so any attention should be focussed on this latest version.

**Comment by RDIL** [comment]
@MikeMcC399 can you send the output with `--trace-deprecation`? I'm personally unable to reproduce it on my end.

**Comment by MikeMcC399** [comment]
@RDIL

The following is from WSL2 under Windows 11 with a virtual Ubuntu 22.04.3 environment and nvm as Node manager installed:

```text
npm install yarn@latest -g
yarn -v
1.22.21
export NODE_OPTIONS='--trace-deprecation'
yarn info yarn description
yarn info v1.22.21
(node:2652) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (/home/mike/.nvm/versions/node/v21.2.0/lib/node_modules/yarn/lib/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/mike/.nvm/versions/node/v21.2.0/lib/node_modules/yarn/lib/cli.js:56536:18)
    at __webpack_require__ (/home/mike/.nvm/versions/node/v21.2.0/lib/node_modules/yarn/lib/cli.js:22:30)
    at Object.<anonymous> (/home/mike/.nvm/versions/node/v21.2.0/lib/node_modules/yarn/lib/cli.js:71815:18)
📦🐈 Fast, reliable, and secure dependency management.
Done in 0.30s.
```

**Comment by Mahi12333** [comment]
(node:15108) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)   .        solve this isseu.

**Comment by shashi-appgolive** [comment]
I m facing same issue while running mongo, this issue resolved ?

**Comment by MikeMcC399** [comment]
@shashi-appgolive 

> I m facing same issue while running mongo, this issue resolved ?

If you are having a problem with mongo then you should probably be referring to their support system https://github.com/mongodb/mongo

**Comment by MikeMcC399** [comment]
@RDIL 

Were you now able to reproduce? and if so, is there still an intention to fix the issue in Yarn Classic?

**Comment by gurkulplus** [comment]
> I m facing same issue while running mongo, this issue resolved ?

Hi @shashi-appgolive is your issues resolved ? I am also getting this on node 19.9.0 version and mongo 7

**Comment by shashi-appgolive** [comment]
> > I m facing same issue while running mongo, this issue resolved ?
> 
> 
> 
> Hi @shashi-appgolive is your issues resolved ? I am also getting this on node 19.9.0 version and mongo 7

Nope! Using local docker with mongo image.

**Comment by luyanda** [comment]
Is there solution to this issue because I can't find one:
(node:9272) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
I don't wan to reproduce it I need to solve it.

**Comment by SeaForeEx** [comment]
I'm seeing that the way to fix this punycode/userland issue in Node is to change ```const punycode = require('punycode');``` to ```const punycode = require('punycode/');```.  I have searched my VSCode file and don't even have the original ```const punycode``` anywhere in my project.  Where would I add this line of code?

**Comment by MikeMcC399** [comment]
@SeaForeEx 

> I'm seeing that the way to fix this punycode/userland issue in Node is to change `const punycode = require('punycode');` to `const punycode = require('punycode/');`. I have searched my VSCode file and don't even have the original `const punycode` anywhere in my project. Where would I add this line of code?

If you don't have the problem directly in your own code, then the problem would be coming from a module you're using. This issue is about the deprecation caused by Yarn Classic itself. I don't believe that it is possible to patch Yarn as a workaround.

You should be able to see which module(s) have a deprecation issue if you execute:

```shell
export NODE_OPTIONS='--trace-deprecation'
yarn
```

If the deprecation is coming from somewhere else rather than Yarn, then you might be able to patch it. That would however be a subject for the module with the issue.

**Comment by SeaForeEx** [comment]
Fixed my issue, I was trying to do this in the Front End instead of the Back End, classic amateur move.

**Comment by RDIL** [comment]
Update: I spoke with the team, it looks like the cause was already identified and fixed, but has not been released yet.

**Comment by JJJ** [comment]
```
→ rm -rf node_modules yarn.lock
took 4s

→ yarn cache clean
success Cleared cache.
✨  Done in 6.47s.

→ node -v
v20.11.0

→ nvm use 21

→ export NODE_OPTIONS='--trace-deprecation'

→ yarn              
→ yarn install    
yarn install v1.22.21
info No lockfile found.
[1/4] 🔍  Resolving packages...
⠁ (node:51023) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:397:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:333:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1006:17)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:56536:18)
    at __webpack_require__ (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:22:30)
    at Object.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:71815:18)
warning @ava/babel > @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
warning @ava/babel > @babel/plugin-proposal-dynamic-import@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
warning @ava/babel > @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
warning @ava/babel > empower-core > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning @ava/babel > babel-plugin-espower > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning @ava/babel > babel-plugin-espower > call-matcher > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning @ava/babel > babel-plugin-espower > espurify > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
warning @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
warning @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
warning @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
warning @electron/rebuild > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
[2/4] 🚚  Fetching packages...
error @ava/typescript@4.1.0: The engine "node" is incompatible with this module. Expected version "^14.19 || ^16.15 || ^18 || ^20". Got "21.6.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
took 45s 🆗
```

**Comment by MikeMcC399** [comment]
@JJJ 

> Also still seeing this.

That is to be expected, since this issue is still open. It was however great to read https://github.com/yarnpkg/yarn/issues/9013#issuecomment-1888289602 which said:

> Update: I spoke with the team, it looks like the cause was already identified and fixed, but has not been released yet.

so that leads me to believe that if we wait, then the fix will be released in a new patch of Yarn > `v1.22.21`.

> Here's my deprecation output:
> ⠁ (node:51023) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
>     at node:punycode:3:9
>     at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:397:7)
>     at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:333:10)
>     at loadBuiltinModule (node:internal/modules/helpers:101:7)
>     at Module._load (node:internal/modules/cjs/loader:1006:17)
>     at Module.require (node:internal/modules/cjs/loader:1237:19)
>     at require (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/v8-compile-cache.js:159:20)
>     at Object.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:56536:18)
>     at __webpack_require__ (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:22:30)
>     at Object.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:71815:18)

This is basically the same stack trace as I posted in https://github.com/yarnpkg/yarn/issues/9013#issuecomment-1823602528.

You then have warnings concerning [@ava/babel](https://www.npmjs.com/package/@ava/babel) which you would need to research in their repo. The same for the other similar warnings.

> error @ava/typescript@4.1.0: The engine "node" is incompatible with this module. Expected version "^14.19 || ^16.15 || ^18 || ^20". Got "21.6.0"
> error Found incompatible module.

This error from [@ava/typescript](https://www.npmjs.com/package/@ava/typescript) says that it is not compatible with Node.js `21`.  It may prevent your migration to Node.js `21`, however this is not a problem that Yarn can help you with.

**Comment by basiq-ash** [comment]
Facing same issue, is there any update on this?

**Comment by MikeMcC399** [comment]
@basiq-ash 

> Facing same issue, is there any update on this?

The last update is from last week. See https://github.com/yarnpkg/yarn/issues/9013#issuecomment-1888289602

**Comment by MikeMcC399** [comment]
The issue is also reproducible if Yarn Classic is used to set the version to Yarn Modern:

```bash
nvm use 21
corepack disable
npm install yarn -g
yarn set version stable
```

```text
$ yarn set version stable
(node:30812) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
➤ YN0000: Retrieving https://repo.yarnpkg.com/4.0.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.0.2.cjs
➤ YN0000: Done in 0s 615ms

```

**Comment by noxidsoft** [comment]
The issue us reproducible using `npm run serve`.

I'm on:
OS: Ubuntu 20.04.6 LTS on Windows 10 x86_64
Kernel: 5.15.133.1-microsoft-standard-WSL2

```(node:47931) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ERROR  TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function```

I am not using a reference in my code.

**Comment by MikeMcC399** [comment]
@noxidsoft 

> `npm run serve`

- You can follow issue https://github.com/vercel/serve/issues/789 for the problem you describe.

Your comment is in the wrong repository, since this issue is about Yarn, not npm, and the problem with the npm module [serve](https://www.npmjs.com/package/serve) is caused by one of its dependencies. It is not caused by Yarn (which you are not using).

**Comment by Hadi90fe** [comment]
I m facing same issue 

Component | Version
-- | --
Yarn (Classic) | v1.22.19
Node.js: | v21.6.1

**Comment by Mohammed-Aljasem** [comment]
Facing the same issue, is there any update on this?

**Comment by emreakdas** [comment]
same issue

**Comment by OzzyCzech** [comment]
same here

**Comment by jigglypop** [comment]
same here

**Comment by MikeMcC399** [comment]
If you want to register that you are also interested in a resolution for this issue, I suggest you "up-vote" it by clicking on the 👍🏻 icon in the original post https://github.com/yarnpkg/yarn/issues/9013#issue-1996377374 instead of adding a separate new comment:

![image](https://github.com/yarnpkg/yarn/assets/66998419/18350b28-c6c8-4258-a1ca-b803fa3c616f)

**Comment by RDIL** [comment]
I don't honestly know. It's not up to me, and Yarn Classic is deprecated in favor of [Berry](https://yarnpkg.com/migration/overview), and is currently only getting high priority updates. I understand that it's not possible in all cases but I highly recommend migrating if you are able.

I'll try to bump this again but I can't guarantee anything.

**Comment by MikeMcC399** [comment]
@RDIL 

Many thanks for your attention to this! I do appreciate that Yarn Classic is deprecated and in terms of using Yarn Classic as a standalone item I would understand if this issue were designated as "won't fix".

I would be more concerned about the use of Yarn Classic in order to set up Yarn Berry (Modern) which provokes the `punycode` warning. Perhaps this is then more of an issue which needs to be transferred to Yarn Berry?

https://yarnpkg.com/getting-started/install says

> The preferred way to manage Yarn is by-project and through [Corepack](https://yarnpkg.com/corepack), a tool shipped by default with Node.js. Modern releases of Yarn aren't meant to be installed globally, or from npm.

This is however slightly problematic as Node.js [Corepack documentation](https://nodejs.org/docs/latest/api/corepack.html) classifies Corepack with [Stability: 1 Experimental](https://nodejs.org/docs/latest/api/documentation.html#stability-index) and the Node.js documentation says "Use of the feature is not recommended in production environments."

So the choice is between the devil and the deep-blue sea in Node.js `21` environments:
- without Corepack means relying on the deprecated Yarn Classic to install Yarn Modern and that provokes the `punycode` deprecation warning
- with Corepack Yarn Modern can be installed without any `punycode` deprecation warning, but at the cost of using the Corepack function which is not recommended for production use

**Comment by MikeMcC399** [comment]
@JhiNResH

Did you run your command using the `--trace-deprecation` option to check which module(s) cause the warning?

**Comment by JhiNResH** [comment]
It did not show up any modules cause the warning

**Comment by stefanrows** [comment]
@JhiNResH same here.

Still getting the error on 21.6.2

**Comment by cba85** [comment]
Same here! Node 21.6.2

## Debug information

```
(node:46025) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:397:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:333:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1006:17)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/clem/dev/wip-telegram-timeline/node_modules/psl/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/clem/dev/wip-telegram-timeline/node_modules/tough-cookie/lib/pubsuffix-psl.js:32:11)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/clem/dev/wip-telegram-timeline/node_modules/tough-cookie/lib/cookie.js:35:17)
```

**Comment by MikeMcC399** [comment]
@cba85 

Your deprecation trace shows also warnings associated with
- https://github.com/lupomontero/psl/issues/315
- https://github.com/salesforce/tough-cookie/pull/346

Those warnings are off topic for this issue however.

**Comment by cba85** [comment]
> @cba85
> 
> Your deprecation trace shows also warnings associated with
> 
> * [punycode is deprecated in Node v21 lupomontero/psl#315](https://github.com/lupomontero/psl/issues/315)
> * [Replace `psl` with `tldts` salesforce/tough-cookie#346](https://github.com/salesforce/tough-cookie/pull/346)
> 
> Those warnings are off topic for this issue however.

Thank you, I will check those links 👍

**Comment by arcanis** [comment]
Fixed with the 1.22.22:

```
❯ corepack yarn@1.22.21 info

yarn info v1.22.21
(node:35285) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
error Received invalid response from npm.
✨  Done in 0.80s.

❯ corepack yarn@1.22.22 info

yarn info v1.22.22
error Received invalid response from npm.
✨  Done in 0.09s.
```

**Comment by dmz006** [comment]
> Fixed with the 1.22.22:
> 
> ```
> ❯ corepack yarn@1.22.21 info
> 
> yarn info v1.22.21
> (node:35285) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> error Received invalid response from npm.
> ✨  Done in 0.80s.
> 
> ❯ corepack yarn@1.22.22 info
> 
> yarn info v1.22.22
> error Received invalid response from npm.
> ✨  Done in 0.09s.
> ```

What is the easiest way to test this fix?

**Comment by MikeMcC399** [comment]
@arcanis 
Many thanks for releasing this fix! 👍🏻 

Testing according to the original repro steps confirms the fix is working as needed: :tada

## Repro steps

Confirm that Node.js 21.x is installed / active

```text
$ node -v
v21.7.1
```

Install previous version of Yarn (`1.22.21`) and confirm that the deprecation warning appears:

```text
$ npm install yarn@1.22.21 -g

added 1 package in 959ms

$ yarn info yarn description
yarn info v1.22.21
(node:25088) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
📦🐈 Fast, reliable, and secure dependency management.
Done in 0.21s.
```

Install latest version of Yarn (`1.22.22`) and confirm that the deprecation warning no longer appears

```text
$ npm install yarn@latest -g

changed 1 package in 459ms

$ yarn info yarn description
yarn info v1.22.22
📦🐈 Fast, reliable, and secure dependency management.
Done in 0.20s.
```

**Comment by MikeMcC399** [comment]
Also confirmed fixed for `yarn set version stable` with `corepack` disabled:

## Repro steps

Confirm that Node.js 21.x is installed / active

```text
$ node -v
v21.7.1
```

Install previous version of Yarn (`1.22.21`) and confirm that the deprecation warning appears:

```text
$ corepack disable

$ npm install yarn@1.22.21 -g

changed 1 package in 604ms

mikem@DESKTOP-J2IBBHJ MINGW64 /d/github2/yarn-install
$ yarn set version stable
(node:7044) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
➤ YN0000: You don't seem to have Corepack enabled; we'll have to rely on yarnPath instead
➤ YN0000: Downloading https://repo.yarnpkg.com/4.1.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.1.1.cjs
➤ YN0000: Done with warnings in 0s 252ms
```

Install latest version of Yarn (`1.22.22`) and confirm that the deprecation warning no longer appears

```text
$ npm install yarn@latest -g

changed 1 package in 440ms

mikem@DESKTOP-J2IBBHJ MINGW64 /d/github2/yarn-install
$ yarn set version stable
➤ YN0000: Downloading https://repo.yarnpkg.com/4.1.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.1.1.cjs
➤ YN0000: Done in 0s 459ms
```

**Comment by MikeMcC399** [comment]
@dmz006 

> What is the easiest way to test this fix?

See my previous comments https://github.com/yarnpkg/yarn/issues/9013#issuecomment-1987106314 and https://github.com/yarnpkg/yarn/issues/9013#issuecomment-1987108485

That does not cover all possible scenarios, however I'm confident that the issue has been fixed now as far as core Yarn is concerned.

**Comment by bennettfrazier** [comment]
> @arcanis Many thanks for releasing this fix! 👍🏻
> 
> Testing according to the original repro steps confirms the fix is working as needed: 🎉
> 
> ### Repro steps
> Confirm that Node.js 21.x is installed / active
> ...
> Install previous version of Yarn (`1.22.21`) and confirm that the deprecation warning appears:
> $ npm install yarn@1.22.21 -g
> ...
> Install latest version of Yarn (`1.22.22`) and confirm that the deprecation warning no longer appears
> ...
> $ npm install yarn@latest -g

@MikeMcC399 Thanks for the steps to reproduce.

I followed these steps, but still getting a punycode DeprecationWarning message.

- Using NVM
- Running Node 21.1.0 (also tested Node 21.7.1)
- Tried both 1.22.21 and 1.22.22 for yarn version

**Comment by MikeMcC399** [comment]
@bennettfrazier 

The most likely reason that you are still getting a punycode deprecation message is that it is coming from a package which is not Yarn. Have you set the environment variable 
`export NODE_OPTIONS='--trace-deprecation'` (or similar depending on your operating system and terminal type)
and run your command to get trace information?

**Comment by aryankarim** [comment]
@MikeMcC399 

I use `node: v21.6.2` and `yarn: 1.22.22`.

Then I ran building `NextJS v.14.2.1`  with `yarn build` with `--trace-deprecation`

Here is the result:
```
(node:24279) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:397:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:333:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1006:17)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at mod.require (/home/UserOne/Desktop/next-test/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at 477 (/home/UserOne/Desktop/next-test/node_modules/next/dist/compiled/node-fetch/index.js:1:104564)
    at __nccwpck_require__ (/home/UserOne/Desktop/next-test/node_modules/next/dist/compiled/node-fetch/index.js:1:453905)
```

**Comment by RDIL** [comment]
@aryankarim 

> at mod.require (/home/UserOne/Desktop/next-test/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at 477 (/home/UserOne/Desktop/next-test/node_modules/next/dist/compiled/node-fetch/index.js:1:104564)
    at __nccwpck_require__ (/home/UserOne/Desktop/next-test/node_modules/next/dist/compiled/node-fetch/index.js:1:453905)

that's not yarn, that's node-fetch bundled within Next

**Comment by aryankarim** [comment]
> that's not yarn, that's node-fetch bundled within Next

You're right I've checked `node-fetch`'s github, they're working on it.

But I still got the warning even with `yarn info yarn description`

However, this upgrade fixed it.

> $ npm install yarn@latest -g

**Comment by leo-milao** [comment]
C:\Users\leo-m\source\repos\dc-monitor>node index.js run
(node:17192) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node-tesseract: Running 'tesseract C:\Users\leo-m\source\repos\dc-monitor/input.jpg C:\Users\leo-m\AppData\Local\Temp\tmp-171926WjMVf1O4q1n -l eng -psm 6'
node-tesseract: Running 'tesseract C:\Users\leo-m\source\repos\dc-monitor/input.jpg C:\Users\leo-m\AppData\Local\Temp\tmp-17192YfR8OTZ1gjiF -l eng -psm 6'
node-tesseract: Deleting 'C:\Users\leo-m\AppData\Local\Temp\tmp-17192YfR8OTZ1gjiF.txt'
node-tesseract: Preprocessor cleanup
node-tesseract: Deleting 'C:\Users\leo-m\AppData\Local\Temp\tmp-171926WjMVf1O4q1n.txt'
node-tesseract: Preprocessor cleanup

**Comment by RDIL** [comment]
Going to be locking this issue because of the influx of comments that are **not caused by Yarn**. If anyone is able to reproduce this bug as a **direct result of Yarn** (using `--trace-deprecation`) after this fix build, please open a new issue. Thanks.
