### ISSUE TITLE
Self signed certificate in certificate chain error

### ISSUE THREAD

**Issue by roby2001** [yarnpkg/yarn#980]
Hey,

I'm trying to move from npm to yarn. I've installed yarn and set up the following config variables : `http-proxy` , `https-proxy` and `strict-ssl` : false.

When I try to `yarn`, at step `[1/4] Resolving packages ` I get the following error :

```
error self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:596:8)
```

As far as I know websockets don't work behind my corporate proxy. Any workarounds ?

**Comment by vbfox** [comment]
Looks the same as #841 ssl settings (like CA or strict ssl) don't work yet 😢

**Comment by roby2001** [comment]
@vbfox thanks! Will close this and follow that :)

**Comment by roby2001** [comment]
@vbfox Thanks! Will follow that post.

**Comment by kittens** [comment]
We've merged support for `cafile` and `strict-ssl` so this issue should be resolved.

**Comment by ptrstpp950** [comment]
@kittens in which version it is or will be released?

**Comment by SoreGums** [comment]
working now in yarn v0.16.0

**Comment by tommck** [comment]
I still get this error with 0.16.1

**Comment by klauern** [comment]
Same here.  I tried just the `cafile` option, then added the `strict-ssl` option and I'm still getting the following from `yarn-error.log`:

```
 C:\Program Files\nodejs\node.exe C:\Users\Me\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js add vue

PATH: ....

Yarn version:
  0.16.1

Node version:
  6.1.0

Platform:
  win32 x64

npm manifest:
  {
    "name": "...",
    "version": "1.0.0",
    "description": "...",
    "main": "index.html",
    "author": "Nick Klauer ...",
    "license": "MIT"
  }

yarn manifest:
  No manifest

bower manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: self signed certificate in certificate chain
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:580:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38)
```

**Comment by mmrath** [comment]
Looks like it works when I specify the config in .yarnrc but not from command line

**Comment by cgatian** [comment]
For me calling `yarn config set "strict-ssl" false` from the CLI updated it as a string parameter to the JSON file, not a boolean. If you open up your `.yarnrc` (located in \Users\<username>\ in Windows) and update to the following, it works.
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
strict-ssl false

**Comment by jeffbski** [comment]
I also found that if I duplicated the strict-ssl and other config from .npmrc into .yarnrc then things started working (or use `yarn config set` to add each part). I'm not sure why it didn't pick it up from .npmrc.

**Comment by damiandennis** [comment]
not working anymore in 0.23.3

**Comment by rmanivannan** [comment]
same with v0.27.5 aswell

```error An unexpected error occurred: "https://registry.npmjs.org/babel-polyfill: self signed certificate in certificate chain".
info If you think this is a bug, please open a bug report with the information provided in "/Users/****/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.```

**Comment by danielmhair** [comment]
I had this same type of error. Doing `yarn config set "strict-ssl" false` resolved the issue for me. Thanks @cgatian

**Comment by monicapeddi021** [comment]
I can't find .yarnrc file in C:/Users. Pls let know how can I create it.

**Comment by danielmhair** [comment]
I never created the file myself. I simply went to the command line and ran `yarn config set "strict-ssl" false`

**Comment by texdc** [comment]
@danielhusar I just tried `yarn config set "strict-ssl" false`, but it didn't work:
```sh
$ yarn --version
1.3.2
```
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


registry "https://nexus.our-private.zone/repository/private-repo/"
lastUpdateCheck 1519057517516
strict-ssl false
```

**Comment by ronaldomoreira** [comment]
I had the same problem on windows 10.

open windows powerShell and enter the following command:
npm config set registry http://registry.npmjs.org/

Then you can use: npm install [your package] normally.

**Comment by ronaldomoreira** [comment]
I had the same problem on windows 10.

open windows powerShell and enter the following command:

    npm config set registry http://registry.npmjs.org/


Then you can use: 

    npm install [your package]

**Comment by ronaldomoreira** [comment]
I had the same problem on windows 10.

open windows powerShell and enter the following command:

    `npm config set registry http://registry.npmjs.org/`


Then you can use: 

    npm install [your package]

**Comment by CosmosHannah** [comment]
> I had this same type of error. Doing `yarn config set "strict-ssl" false` resolved the issue for me. Thanks @cgatian

Yes, I have the same error when running `yarn install`. That commend works for me too. :)

**Comment by Exadra37** [comment]
Recommending to set `strict-ssl` to `false` is like leaving home with doors and windows open, and say come in and take all you want ;)

Please don't work around issues, and instead fix them properly.

So enable ssl strict:
```
yarn config set strict-ssl true
```

And then tell `yarn` where to find the certificate file:
```
yarn config set cafile /path/to/certificate/file
```

**Comment by cgatian** [comment]
Works great if you have the certificate. How do you fix without?

**Comment by Exadra37** [comment]
> Works great if you have the certificate. How do you fix without?

When you get this error is because your computer is not able to communicate directly with the url being requested, maybe because your are behind a corporate firewall or proxy that uses a custom self signed certificate, therefore in either cases you need to ask the administrator of your network to provide you the certificate.

**Comment by FranklinYu** [comment]
@cgatian Typically you have access to the certificate (you simply don’t know how to download it). Most registry software support TLS.

**Comment by Nathan187** [comment]
@Exadra37 where is the certificate file?  how do i know it exists, etc?

**Comment by Exadra37** [comment]
@Nathan187 you need to ask your Network Administrator to give you the file and then tell yarn where you have placed it.

**Comment by Emzawadzki** [comment]
On **MacOS** the certificate should be in keychain - there you can display info about it and by extending "trust settings" (or something similar - I have non-EN OS) and set to "Always trust" for SSL - that's what fixed company's certificate in my case for both yarn and npm

**Comment by valenfv** [comment]
I tried `yarn config set cafile /path/to/certificate/file` but didn't work either....

**Comment by ff0041** [comment]
On Ubuntu 20.04, use `yarn config set cafile /etc/ssl/certs/ca-certificates.crt`, after adding the CA to `/etc/ssl/certs/` and running `update-ca-certificates`.

**Comment by ad34** [comment]
this issue is back since I upgraded to yarn 3, setting yarn config set  enableStrictSettings false does not fix the issue

**Comment by kenmlee** [comment]
for yarn v2/3, run:

yarn config set enableStrictSsl false

**Comment by jakeboone02** [comment]
For anyone who couldn't get any of the solutions mentioned in this thread to work, the only thing that ended up working on my work computer was to get the certificate file from my IT department then set the `NODE_EXTRA_CA_CERTS` environment variable to the path to that file. (I also had `strict-ssl` set to `false` but I'm not sure if that was necessary.)

**Comment by Exadra37** [comment]
>  (I also had strict-ssl set to false but I'm not sure if that was necessary.)
You are running in insecure mode now, thus defeating the security that your IT department wants to enforce company wide.

**Comment by jakeboone02** [comment]
> > (I also had strict-ssl set to false but I'm not sure if that was necessary.)
> 
> You are running in insecure mode now, thus defeating the security that your IT department wants to enforce company wide.

Right, I understand that and certainly didn't mean to imply that I was _recommending_ setting `strict-ssl` to `false`. I was just clarifying my setup at the time in case anyone gets in the same situation in the future.

**Comment by Exadra37** [comment]
>  I was just clarifying my setup at the time in case anyone gets in the same situation in the future.

So, you are indeed recommending/endorsing a poor security solution by saying this.

**Comment by john8329** [comment]
Yarn relies on Node. As mentioned by @jakeboone02, node has an environment variable for adding a custom CA to the existing ones, without replacing:
`export NODE_EXTRA_CA_CERTS="$HOME/.my-ca.crt"`.

Set this to your `.zshenv` or `.bashrc` and it should work. I find it very clean and modular. Do NOT disable `strict-ssl`, it completely throws off security.
Posting this in case somebody else stumbles on this and still has doubts.

**Comment by thedamon** [comment]
We had this happen to some users only on Windows for a few packages and I definitely don't understand what cert is supposed to be where

**Comment by maxpetts** [comment]
Had to use: `yarn config set enableStrictSsl false`, as strict-ssl config name seems to have changed.

**Comment by aep-sunlife** [comment]
Same issue in yarn 4.5.0. Do not advise disabling SSL.

That's apart from corepack's own problems integrating with proxies and self signed certificate chains.

**Comment by stephwongwt** [comment]
I'm using Yarn 4.6.0, and using `yarn config set httpsCaFilePath <path-to-cert-pems>` helped. This is provided you can get the cert pems for your CA.
